import os
import shutil
import subprocess
import sys
from dotenv import load_dotenv


def build():
    root_dir = os.path.dirname(os.path.abspath(__file__))
    dist_dir = os.path.join(root_dir, "dist")
    build_dir = os.path.join(root_dir, "build")
    config_file = os.path.join(root_dir, "client_config.py")

    # Load secrets from .env if available
    load_dotenv(os.path.join(root_dir, ".env"))

    client_key = os.getenv("DASHBOARD_PASSWORD", "DEFAULT_SECRET")

    # Stage uncommitted source code changes
    try:
        status = subprocess.check_output(
            ["git", "status", "--porcelain"], cwd=root_dir, stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
        if status:
            print("[Build] Staging source code changes...")
            subprocess.check_call(["git", "add", "-A"], cwd=root_dir)
            print("[Build] Creating git release commit...")
            subprocess.check_call(["git", "commit", "-m", "build: update release binaries"], cwd=root_dir)
    except Exception as e:
        print(f"[Build Note] Git pre-commit skipped: {e}")

    try:
        git_hash = (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"], cwd=root_dir, stderr=subprocess.DEVNULL
            )
            .decode("utf-8")
            .strip()
        )
    except Exception:
        git_hash = "unknown"

    print(f"[Build] Etching CLIENT_KEY and CLIENT_VERSION ({git_hash}) into binary build config...")
    with open(config_file, "w", encoding="utf-8") as f:
        f.write(
            f"# Generated by build.py - DO NOT COMMIT TO GIT\n"
            f"CLIENT_KEY = {repr(client_key)}\n"
            f"CLIENT_VERSION = {repr(git_hash)}\n"
        )

    try:
        print("[Build] Installing dependencies from requirements.txt...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"]
        )

        print("\n[Build] Compiling client.py -> run.exe...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "run",
                "client.py",
            ],
            cwd=root_dir,
        )

        print("\n[Build] Compiling installer.py -> installer.exe...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "installer",
                "installer.py",
            ],
            cwd=root_dir,
        )

        run_dist = os.path.join(dist_dir, "run.exe")
        installer_dist = os.path.join(dist_dir, "installer.exe")

        run_target = os.path.join(root_dir, "run.exe")
        installer_target = os.path.join(root_dir, "installer.exe")

        if os.path.exists(run_dist):
            shutil.copy2(run_dist, run_target)
            print(f"[Build] Successfully copied run.exe to root -> {run_target}")

        if os.path.exists(installer_dist):
            shutil.copy2(installer_dist, installer_target)
            print(
                f"[Build] Successfully copied installer.exe to root -> {installer_target}"
            )

        # Stage compiled binaries and amend release commit
        try:
            print("\n[Build] Staging compiled binaries (run.exe, installer.exe)...")
            subprocess.check_call(["git", "add", "run.exe", "installer.exe"], cwd=root_dir)
            subprocess.check_call(["git", "commit", "--amend", "--no-edit"], cwd=root_dir)
            print("[Build] Pushing release commit and binaries to GitHub...")
            subprocess.check_call(["git", "push"], cwd=root_dir)
            print("[Build] Successfully pushed updated release binaries to GitHub!")
        except Exception as e:
            print(f"[Build Note] Git push skipped/failed: {e}")

    finally:
        print("\n[Build] Cleaning up temporary build artifacts and etched config...")
        if os.path.exists(config_file):
            os.remove(config_file)
            print(f"[Build] Removed temporary {config_file}")
        if os.path.exists(build_dir):
            shutil.rmtree(build_dir, ignore_errors=True)
        if os.path.exists(dist_dir):
            shutil.rmtree(dist_dir, ignore_errors=True)

        for spec in ["run.spec", "installer.spec"]:
            spec_path = os.path.join(root_dir, spec)
            if os.path.exists(spec_path):
                os.remove(spec_path)

    print(
        "\n[Build Complete] Both run.exe and installer.exe are ready and synced with GitHub!"
    )


if __name__ == "__main__":
    build()
