import os
import shutil
import subprocess
import sys
from dotenv import load_dotenv


def build():
    root_dir = os.path.dirname(os.path.abspath(__file__))
    dist_dir = os.path.join(root_dir, "dist")
    build_dir = os.path.join(root_dir, "build")
    config_file = os.path.join(root_dir, "client_config.py")

    # Load secrets from .env if available
    load_dotenv(os.path.join(root_dir, ".env"))

    client_key = os.getenv("CLIENT_KEY") or os.getenv("DASHBOARD_PASSWORD")
    if not client_key:
        print("[Build Warning] Neither CLIENT_KEY nor DASHBOARD_PASSWORD is set in .env / environment.")
        print("[Build Warning] Using default placeholder key.")
        client_key = "DEFAULT_SECRET"

    print(f"[Build] Etching CLIENT_KEY into binary build config...")
    with open(config_file, "w", encoding="utf-8") as f:
        f.write(f'# Generated by build.py - DO NOT COMMIT TO GIT\nCLIENT_KEY = {repr(client_key)}\n')

    try:
        print("[Build] Installing dependencies from requirements.txt...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"]
        )

        print("\n[Build] Compiling client.py -> run.exe...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "run",
                "client.py",
            ],
            cwd=root_dir,
        )

        print("\n[Build] Compiling installer.py -> installer.exe...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "installer",
                "installer.py",
            ],
            cwd=root_dir,
        )

        run_dist = os.path.join(dist_dir, "run.exe")
        installer_dist = os.path.join(dist_dir, "installer.exe")

        run_target = os.path.join(root_dir, "run.exe")
        installer_target = os.path.join(root_dir, "installer.exe")

        if os.path.exists(run_dist):
            shutil.copy2(run_dist, run_target)
            print(f"[Build] Successfully copied run.exe to root -> {run_target}")

        if os.path.exists(installer_dist):
            shutil.copy2(installer_dist, installer_target)
            print(
                f"[Build] Successfully copied installer.exe to root -> {installer_target}"
            )

    finally:
        print("\n[Build] Cleaning up temporary build artifacts and etched config...")
        if os.path.exists(config_file):
            os.remove(config_file)
            print(f"[Build] Removed temporary {config_file}")
        if os.path.exists(build_dir):
            shutil.rmtree(build_dir, ignore_errors=True)
        if os.path.exists(dist_dir):
            shutil.rmtree(dist_dir, ignore_errors=True)

        for spec in ["run.spec", "installer.spec"]:
            spec_path = os.path.join(root_dir, spec)
            if os.path.exists(spec_path):
                os.remove(spec_path)

    print(
        "\n[Build Complete] Both run.exe and installer.exe are ready in the project root!"
    )


if __name__ == "__main__":
    build()
