import os
import shutil
import subprocess
import sys
from dotenv import load_dotenv


def build():
    root_dir = os.path.dirname(os.path.abspath(__file__))
    dist_dir = os.path.join(root_dir, "dist")
    build_dir = os.path.join(root_dir, "build")
    config_file = os.path.join(root_dir, "client_config.py")

    # Load secrets from .env if available
    load_dotenv(os.path.join(root_dir, ".env"))

    client_key = os.getenv("DASHBOARD_PASSWORD", "DEFAULT_SECRET")

    print("[Build] Etching CLIENT_KEY into binary build config...")
    with open(config_file, "w", encoding="utf-8") as f:
        f.write(
            f"# Generated by build.py - DO NOT COMMIT TO GIT\n"
            f"CLIENT_KEY = {repr(client_key)}\n"
        )

    try:
        print("[Build] Installing dependencies from requirements.txt...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"]
        )

        ext = ".exe" if sys.platform == "win32" else ""
        run_bin = f"run{ext}"
        installer_bin = f"installer{ext}"

        print(f"\n[Build] Compiling client.py -> {run_bin}...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "run",
                "client.py",
            ],
            cwd=root_dir,
        )

        print(f"\n[Build] Compiling installer.py -> {installer_bin}...")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--noconsole",
                "--onefile",
                "--clean",
                "-n",
                "installer",
                "installer.py",
            ],
            cwd=root_dir,
        )

        run_dist = os.path.join(dist_dir, run_bin)
        installer_dist = os.path.join(dist_dir, installer_bin)

        run_target = os.path.join(root_dir, run_bin)
        installer_target = os.path.join(root_dir, installer_bin)

        if os.path.exists(run_dist):
            shutil.copy2(run_dist, run_target)
            if sys.platform != "win32":
                os.chmod(run_target, 0o755)
            print(f"[Build] Successfully copied {run_bin} to root -> {run_target}")

        if os.path.exists(installer_dist):
            shutil.copy2(installer_dist, installer_target)
            if sys.platform != "win32":
                os.chmod(installer_target, 0o755)
            print(
                f"[Build] Successfully copied {installer_bin} to root -> {installer_target}"
            )

        # Stage all changes and compiled binaries in a single clean commit
        try:
            status = (
                subprocess.check_output(
                    ["git", "status", "--porcelain"], cwd=root_dir, stderr=subprocess.DEVNULL
                )
                .decode("utf-8")
                .strip()
            )
            if status:
                print("\n[Build] Staging changes and compiled binaries...")
                subprocess.check_call(["git", "add", "-A"], cwd=root_dir)
                commit_msg = "build: update release binaries"
                print(f"[Build] Creating single release commit: \"{commit_msg}\"...")
                subprocess.check_call(["git", "commit", "-m", commit_msg], cwd=root_dir)
                print("[Build] Pushing release commit and binaries to GitHub...")
                subprocess.check_call(["git", "push"], cwd=root_dir)
                print("[Build] Successfully pushed updated release binaries to GitHub!")
            else:
                print("\n[Build] Working tree clean; nothing new to commit.")
        except Exception as e:
            print(f"[Build Note] Git commit/push skipped or failed: {e}")

    finally:
        print("\n[Build] Cleaning up temporary build artifacts and etched config...")
        if os.path.exists(config_file):
            os.remove(config_file)
            print(f"[Build] Removed temporary {config_file}")
        if os.path.exists(build_dir):
            shutil.rmtree(build_dir, ignore_errors=True)
        if os.path.exists(dist_dir):
            shutil.rmtree(dist_dir, ignore_errors=True)

        for spec in ["run.spec", "installer.spec"]:
            spec_path = os.path.join(root_dir, spec)
            if os.path.exists(spec_path):
                os.remove(spec_path)

    print(
        "\n[Build Complete] Both run.exe and installer.exe are ready and synced with GitHub!"
    )


if __name__ == "__main__":
    build()
